### ISSUE TITLE
EEG and Dipole Plot images do not load

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [OpenSourceBrain/OSBv2#696]
**Describe the bug**
In the NetPyNE integration, Dipole plot and EEG plot images do not load

**To Reproduce**
1. Go to the homepage
2. Create a NetPyNE workspace
3. open the workspace with NetPyNE
4. On NetPyNE, load tutorial 1
5. Go to Configuration > recording, and check the box for 'record dipole using lfpykit'
6. Create and simulate network
7. Click on the EEG and Dipole plots

Note that the EEG and Dipole Plots are images 

**Expected behavior**
The EEG and Dipole Plots should be displayed as in NetPyNE
![image](https://user-images.githubusercontent.com/99416933/222698236-dbe3d58f-c900-4551-9fa9-bedf2f13f7b7.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/99416933/222697712-7afd660f-6d4d-47d5-9137-dee338867b8e.png)

**Comment by filippomc** [comment]
@pgleeson need to pull the lastest on your branch osbv2-dev. 

What are the changes that you've put there? If just about dependencies we can achieve that on osb without using a separate branch, which would help keeping things up to date with the lates

**Comment by pgleeson** [comment]
@filippomc Will look into that now...

**Comment by pgleeson** [comment]
See https://github.com/OpenSourceBrain/OSBv2/issues/580#issuecomment-1488271129. Best to use latest osbv2 branch

**Comment by filippomc** [comment]
Get the following error currently with the release/1.0.0 branch of netpyne 

```
---------------------------------------------------------------------------
StdinNotImplementedError                  Traceback (most recent call last)
~/netpyne/netpyne_ui/netpyne_geppetto.py in getPlot(self, plotName, LFPflavour, theme)
    885                 else:
--> 886                     fig_data = getattr(analysis, plotName)(**args)
    887                     if isinstance(fig_data, tuple):

/opt/conda/lib/python3.7/site-packages/netpyne/analysis/dipole.py in plotEEG(showCell, showPop, timeRange, dipole_location, dpi, figSize, showFig, saveFig)
     79 
---> 80     nyhead = NYHeadModel()
     81 

/opt/conda/lib/python3.7/site-packages/lfpykit/eegmegcalc.py in __init__(self, nyhead_file)
   1390 
-> 1391         self._load_head_model(nyhead_file)
   1392 

/opt/conda/lib/python3.7/site-packages/lfpykit/eegmegcalc.py in _load_head_model(self, nyhead_file)
   1411             print("New York head-model file not found: %s" % self.head_file)
-> 1412             yn = input(f"Download as {self.head_file} (710 MB)? [y/n]: ")
   1413             if yn == 'y':

/opt/conda/lib/python3.7/site-packages/ipykernel/kernelbase.py in raw_input(self, prompt)
    845             raise StdinNotImplementedError(
--> 846                 "raw_input was called, but this frontend does not support input requests."
    847             )

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-175-e68b490aea47> in <module>
----> 1 netpyne_geppetto.getPlot(utils.convertToPython('"plotEEG"'),utils.convertToPython('false'),utils.convertToPython('"gui"'))

~/netpyne/netpyne_ui/netpyne_geppetto.py in getPlot(self, plotName, LFPflavour, theme)
    906                           return fig_data
    907         except Exception as e:
--> 908             err = "There was an exception in %s():" % (e.plotName)
    909             logging.exception(("%s \n %s \n%s" % (err, e, sys.exc_info())))
    910 

AttributeError: 'StdinNotImplementedError' object has no attribute 'plotName'
```

**Comment by filippomc** [comment]
@pgleeson we have a [fix](https://github.com/suny-downstate-medical-center/netpyne/pull/749#issuecomment-1504241525) on Netpyne, can you please update your branch to include current release/v1.0.4.1?

**Comment by filippomc** [comment]
@pgleeson cannot build netpyne as pip doesn't like the version name

```
#31 4.898   Traceback (most recent call last):                                                                                                 
#31 4.898     File "<string>", line 1, in <module>                                                                                             
#31 4.898     File "/tmp/pip-req-build-qsny8tpz/setup.py", line 95, in <module>                                                                
#31 4.898       entry_points={},                                                                                                               
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 108, in setup                                         
#31 4.898       return distutils.core.setup(**attrs)                                                                                           
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 147, in setup                                  
#31 4.898       _setup_distribution = dist = klass(attrs)                                                                                      
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 483, in __init__                                          
#31 4.898       self.patch_missing_pkg_info(attrs)                                                                                             
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 472, in patch_missing_pkg_info                            
#31 4.898       dist._version = _normalization.safe_version(str(attrs['version']))                                                             
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/_normalization.py", line 65, in safe_version                             
#31 4.898       return str(packaging.version.Version(attempt))                                                                                 
#31 4.898     File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__                     
#31 4.898       raise InvalidVersion(f"Invalid version: '{version}'")                                                                          
#31 4.898   setuptools.extern.packaging.version.InvalidVersion: Invalid version: '1.0.4.1-osbv2'
```

**Comment by pgleeson** [comment]
Strange... as it had an underscore in the version name, and changed it somewhere to a -. I see you changed it to `1.0.4.1+osbv2` now...

**Comment by filippomc** [comment]
Yes the new convention uses the + for additional characters in the version name
