### ISSUE TITLE
NWB explorer build failing

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#794]
https://github.com/OpenSourceBrain/OSBv2/actions/runs/6561681930/job/17821900854

```
#32 9.685 Traceback (most recent call last):
#32 9.685   File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 232, in _resolve_classes
#32 9.686     klass = self._resolve_string(klass)
#32 9.686   File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 2025, in _resolve_string
#32 9.688     return import_item(string)
#32 9.688   File "/opt/conda/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 31, in import_item
#32 9.689     module = __import__(package, fromlist=[obj])
#32 9.689 ModuleNotFoundError: No module named 'jupyter_server.contents'
#32 9.689 
#32 9.689 During handling of the above exception, another exception occurred:
#32 9.689 
#32 9.689 Traceback (most recent call last):
#32 9.689   File "/opt/conda/bin/jupyter-notebook", line 10, in <module>
#32 9.689     sys.exit(main())
#32 9.689   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 280, in launch_instance
#32 9.690     super().launch_instance(argv=argv, **kwargs)
#32 9.690   File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 1051, in launch_instance
#32 9.691     app = cls.instance(**kwargs)
#32 9.691   File "/opt/conda/lib/python3.9/site-packages/traitlets/config/configurable.py", line 575, in instance
#32 9.692     inst = cls(*args, **kwargs)
#32 9.692   File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1311, in __new__
#32 9.693     inst.setup_instance(*args, **kwargs)
#32 9.693   File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1354, in setup_instance
#32 9.694     super(HasTraits, self).setup_instance(*args, **kwargs)
#32 9.694   File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1330, in setup_instance
#32 9.694     init(self)
#32 9.694   File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 223, in instance_init
#32 9.695     self._resolve_classes()
#32 9.695   File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
#32 9.695     warn(f"{klass} is not importable. Is it installed?", ImportWarning)
#32 9.695 TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
#32 9.747 Error installing NWB-Explorer
```

**Comment by pgleeson** [comment]
Any insight on this @filippomc? Getting this error also on the DANDI showcase project: https://github.com/OpenSourceBrain/DANDIArchiveShowcase/actions

**Comment by filippomc** [comment]
Looking into this. That's a broken dependency in the jupyter stack (traitlets > 5.9.0) so need to find the right combination of packages that works

**Comment by filippomc** [comment]
The above issue is fixed on the docker build but still there are issues in the basic dev setup as it doesn't use requirements.txt, which pins specific versions of the jupyter libraries which are not affected. It also appears that the latest pynwb does not support python 3.7. Should we remove support as well?

**Comment by pgleeson** [comment]
Fixed
