### ISSUE TITLE
Jupyterlab and Netpyne new builds:  Back-off restarting failed container

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#832]
**Describe the bug**
When opening a workspace:

![image](https://github.com/OpenSourceBrain/OSBv2/assets/46561561/c1742207-806d-4a5e-974a-d044737500f6)

This is most probably related to the jupyter stack dependencies

**Comment by filippomc** [comment]
Entered start.sh with args: jupyterhub-singleuser --ip=0.0.0.0 --port=8000 --debug --NotebookApp.default_url=/lab --NotebookApp.notebook_dir=/opt/workspace
Executing the command: jupyterhub-singleuser --ip=0.0.0.0 --port=8000 --debug --NotebookApp.default_url=/lab --NotebookApp.notebook_dir=/opt/workspace
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 232, in _resolve_classes
    klass = self._resolve_string(klass)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 2018, in _resolve_string
    return import_item(string)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 7, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import main
  File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/app.py", line 18, in <module>
    SingleUserNotebookApp = make_singleuser_app(App)
  File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 815, in make_singleuser_app
    empty_parent_app = App()
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1294, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1337, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1313, in setup_instance
    init(self)
  File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 223, in instance_init
    self._resolve_classes()
  File "/opt/conda/lib/python3.9/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'

**Comment by SimaoBolota-MetaCell** [comment]
No longer getting the `Back-off restarting failed container` but now am getting `Only admins can spawn on behalf of other users` for NetPyNE and NWB Explorer inside osb


![Image](https://github.com/OpenSourceBrain/OSBv2/assets/99416933/46998144-69a6-4673-baf5-149fc85fd7fc)

@filippomc
